apiVersion: v1
kind: Pod
metadata:
   name: result-pod
   labels:
      name: result-pod
      app: demo-votingapp-pod
spec:
   containers:
     - name: result-pod
       image: dockersamples/examplevotingapp_result
       ports: 
         containerPort: 80 
