apiVersion: v1
kind: Pod
metadata:
   name: votingapp-pod
   labels:
      name: votingapp-pod
      app: demo-votingapp-pod
spec:
   containers:
     - name: votingapp-pod
       image: dockersamples/examplevotingapp_vote
       ports: 
         containerPort: 80 
