apiVersion: v1
kind: Pod
metadata:
   name: worker-pod
   labels:
      name: worker-pod
      app: demo-votingapp-pod
spec:
   containers:
     - name: worker-pod
       image: dockersamples/examplevotingapp_worker
       ports: 
         containerPort: 80 
